<?php

namespace App\Models;

use App\Notifications\ManagerResetPassword;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class Accountant extends Authenticatable
{
    use Notifiable, HasRoles;
    protected $table = 'accountants';
    protected $guarded = [];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (!request()->is('manager/accountants') && !request()->is('manager/accountants/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }


    public function recipients()
    {
        return $this->hasMany(Recipients::class,'accountant_id','id');
    }
    public function payments()
    {
        return $this->hasMany(Payment::class,'accountant_id','id');
    }
    public function setLanguage()
    {
        $locale = $this->local ?? config("app.fallback_locale");
        app()->setLocale($locale);
    }

    public function getTotalRecipientsAttribute()
    {
        $total_payments = $this->payments()->sum('amount');
        $total_recipients = Recipients::where('accountant_id',$this->id)->sum('amount');
        return abs($total_payments - $total_recipients);
}

    public function getActionButtonsAttribute()
    {
        $route = 'accountants';
        $button = '';
        $button .= '<a href="' . route('manager.' . $route . '.edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
//        $button .= '<a href="' . route('manager.' . $route . '.show', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-eye"></i></a> ';
        $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';

        return $button;
    }

}
