<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Pivot;

class Bill extends Pivot
{
    protected $table = 'bills';
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (!request()->is('manager/bills') && !request()->is('manager/bills/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }

    public function client()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function items()
    {
        return $this->belongsToMany(Item::class, BillItems::class, 'bill_id', 'item_id')->withPivot(
            [
                'item_id',
                'bill_id',
                'cost_before',
                'cost_after',
                'quantity',
                'total_cost',
            ])
            ->using(BillItems::class)
//            ->as('category_regions')//renaming the pivot table
            ->withTimestamps();
    }

    public function getUuidAttribute($value)
    {
        return "#" . $value;
    }

    public function getActionButtonsAttribute()
    {
        $route = 'bills';
        $button = '';
        $button .= '<a href="' . route('manager.' . $route . '.edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
//        $button .= '<a href="' . route('manager.' . $route . '.show', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-eye"></i></a> ';
        $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';

        return $button;
    }

}
