<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Database\Eloquent\Model;


class Payment
    extends Model
{
    protected $table = 'payments';
    protected $guarded = [];


//    payment type
    public const BILL = 1;
    public const CDS = 2;
    public const CDS2 = 3;

    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (!request()->is('manager/bills') && !request()->is('manager/bills/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }


    public function bill()
    {
        return $this->belongsTo(Bill::class, 'bill_id', 'id');
    }

        public function cds()
    {
        return $this->belongsTo(CDs::class, 'creditor_debtor_id', 'id');
    }

//    attributes
    public function getTypeNameAttribute()
    {
        switch ($this->type) {
            case self::CDS:
                return t('Cds');
                case self::CDS2:
                return t('Cds2');

            case self::BILL:
                return t('Bill');
            default:
                return t('Un known status');
        }
    }

    public function getActionButtonsAttribute()
    {
        $route = 'payments';
        $button = '';
        if (auth()->guard('manager')->check()){
            $button .= '<a href="' . route('manager.' . $route . '.edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
            $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        }else if (auth()->guard('accountant')->check()){
//            $button .= '<a href="' . route('manager.' . $route . '.edit', $this->id) . '" class="btn btn-icon btn-danger disabled "><i class="la la-pencil"></i></a> ';
//            $button .= '<button disabled type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        }
        else if (auth()->guard('client')->check()){
//            $button .= '<a href="' . route('manager.' . $route . '.edit', $this->id) . '" class="btn btn-icon btn-danger disabled "><i class="la la-pencil"></i></a> ';
//            $button .= '<button disabled type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        }
        return $button;
    }

//Scopes

    public function scopeBill($query)
    {
        return $query->where('type', self::BILL);
    }

    public function scopeCds($query)
    {
        return $query->where('type', self::CDS);
    }
}
