<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Illuminate\Database\Eloquent\Model;


class Recipients
    extends Model
{
    protected $table = 'recipients';
    protected $guarded = [];

//creditor_debtor Types
    public const CREDITOR = 1;//ديوني عند الناس
    public const DEBTOR = 2;//الديون المطلوبة دفعها للناس

    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (!request()->is('manager/bills') && !request()->is('manager/bills/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }

    public function accountant()
    {
        return $this->belongsTo(Accountant::class, 'accountant_id', 'id');
    }

    public function manager()
    {
        return $this->belongsTo(Manager::class, 'manager_id', 'id');
    }


//    attributes
    public function getActionButtonsAttribute()
    {
        $button = '';
        $route = 'recipients';
        if (auth()->guard('manager')->check()) {
            $button .= '<a href="' . route('manager.' . $route . '.edit', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-pencil"></i></a> ';
//        $button .= '<a href="' . route('manager.' . $route . '.show', $this->id) . '" class="btn btn-icon btn-danger "><i class="la la-eye"></i></a> ';
            $button .= '<button type="button" data-id="' . $this->id . '" data-toggle="modal" data-target="#deleteModel" class="deleteRecord btn btn-icon btn-danger"><i class="la la-trash"></i></button>';
        }
        return $button;
    }

}
