<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Setting extends Model
{
    protected $table = 'settings';
    protected $guarded = [];
    public const DIR_IMAGE_UPLOADS = 'settings';
    public const URL = 'settings';


    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (request()->is('api/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }

    static public function getSettings()
    {
        $settings = Cache::remember('settings', 60, function () {
            return self::select('key', 'value')->get();
        });
        return $settings;
    }
}
